### ISSUE TITLE
Fill colour

### ISSUE THREAD

**Issue by fatuhoku** [akiroom/AXWireButton#2]
It'd be great if you could make a button like this:

![screen shot 2015-02-13 at 22 11 49](https://cloud.githubusercontent.com/assets/430233/6196117/5fe5adbe-b3cd-11e4-8f95-b869e7aad798.png)

**Comment by akiroom** [comment]
@fatuhoku Thank you for your nice comment! I implement this idea in ver 1.0.0 today. Please check it  and sorry for the late reply😂
